package themer

func GenerateGTKCSS(theme Theme) string {

	var content string

	content += "# This file is generated by themer. Changes may be overwritten.\n"
	content += "@define-color base00 #" + theme.Base00 + ";\n"
	content += "@define-color base01 #" + theme.Base00 + ";\n"
	content += "@define-color base02 #" + theme.Base00 + ";\n"
	content += "@define-color base03 #" + theme.Base00 + ";\n"
	content += "@define-color base04 #" + theme.Base00 + ";\n"
	content += "@define-color base05 #" + theme.Base00 + ";\n"
	content += "@define-color base06 #" + theme.Base00 + ";\n"
	content += "@define-color base07 #" + theme.Base00 + ";\n"
	content += "@define-color base08 #" + theme.Base00 + ";\n"
	content += "@define-color base09 #" + theme.Base00 + ";\n"
	content += "@define-color base0A #" + theme.Base00 + ";\n"
	content += "@define-color base0B #" + theme.Base00 + ";\n"
	content += "@define-color base0C #" + theme.Base00 + ";\n"
	content += "@define-color base0D #" + theme.Base00 + ";\n"
	content += "@define-color base0E #" + theme.Base00 + ";\n"
	content += "@define-color base0F #" + theme.Base00 + ";\n"

	return content
}
