package themer

import (
	"fmt"
	"os"
)

func updateTmuxConfig() {

}

func ApplyTmux(theme Theme) error {

	var content string

	content = fmt.Sprintf(`
    # This file is generated by themer. Changes may be overwritten.\n

    set-window-option -g window-status-current-style fg="#%s"
    set -g status-bg "#%s"
    set -g status-fg "#%s"

    set-option -g pane-active-border-style fg='#%s'

  `, theme.Base08, theme.Base01, theme.Base05, theme.Base0D)

	configPath := os.Getenv("HOME") + "/.config/tmux/themer.conf"

	writeErr := os.WriteFile(configPath, []byte(content), 0644)
	if writeErr != nil {
		return writeErr
	}

	return nil
}
