package themer

import (
	"fmt"
	"os"

	"github.com/spf13/viper"
)

func applyPrompt(theme Theme) error {

	if viper.GetBool("zsh.enable") == false {
		return nil
	}

	configPath := viper.GetString("zsh.path")

	content := fmt.Sprintf(`
    # This file is generated by themer. Changes may be overwritten.
    COL_NAME='%s'
    COL_DIR='%s'
    COL_GIT='%s'
  `, theme.Base0A, theme.Base0D, theme.Base0E)

	writeErr := os.WriteFile(configPath, []byte(content), 0644)
	if writeErr != nil {
		return writeErr
	}

	return nil
}


func ApplyZsh(theme Theme) error {

	applyPrompt(theme)

	return nil
}
