package themer

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/spf13/viper"
)

func updateTmuxConfig() {
	cmd := exec.Command("tmux", "source-file", os.Getenv("HOME") + "/.config/tmux/tmux.conf")

	_, err := cmd.Output()
	if err != nil {
		fmt.Println("Error:", err)
		return
	}
}

func ApplyTmux(theme Theme) error {

	if viper.GetBool("tmux.enable") == false {
		return nil
	}

	configPath := viper.GetString("tmux.path")

	var content string

	content = fmt.Sprintf(`
    # This file is generated by themer. Changes may be overwritten.\n

    set-window-option -g window-status-current-style fg="#%s"
    set -g status-bg "#%s"
    set -g status-fg "#%s"

    set-option -g pane-active-border-style fg='#%s'

  `, theme.Base08, theme.Base01, theme.Base05, theme.Base0D)

	writeErr := os.WriteFile(configPath, []byte(content), 0644)
	if writeErr != nil {
		return writeErr
	}

	updateTmuxConfig()

	return nil
}
